// Shared styles for Learn mode components

export const STYLES = {
    noteBadge: {
        fontSize: '0.7rem',
        background: 'var(--bg-primary)',
        padding: '0.15rem 0.4rem',
        borderRadius: '6px',
        color: 'var(--text-primary)',
        fontWeight: 500,
    },
    noteBadgeSmall: {
        fontSize: '0.6rem',
        background: 'var(--bg-primary)',
        padding: '0.1rem 0.3rem',
        borderRadius: '4px',
        color: 'var(--text-primary)',
    },
    melodyBadgePrimary: {
        fontSize: '0.7rem',
        background: 'var(--color-cyan-dim)',
        padding: '0.2rem 0.5rem',
        borderRadius: '999px',
        border: '2px solid var(--color-cyan)',
        color: 'var(--color-cyan)',
        fontWeight: 'bold',
        cursor: 'pointer',
        userSelect: 'none',
    },
    melodyBadgeSecondary: {
        fontSize: '0.65rem',
        background: 'var(--bg-primary)',
        padding: '0.1rem 0.35rem',
        borderRadius: '999px',
        border: '1px solid var(--color-cyan-border)',
        color: 'var(--color-cyan)',
    },
    chordBadge: {
        fontSize: '0.7rem',
        fontWeight: 'bold',
        color: 'var(--color-pink-bright)',
        cursor: 'pointer',
        padding: '0.2rem 0.5rem',
        borderRadius: '999px',
        background: 'var(--color-pink-dim)',
        border: '2px solid var(--color-pink)',
        transition: 'all var(--transition-fast)',
        userSelect: 'none',
        display: 'inline-block',
    },
    sectionLabel: {
        fontSize: '0.6rem',
        color: 'var(--text-tertiary)',
        marginBottom: '0.2rem',
        textTransform: 'uppercase',
        letterSpacing: '0.08em',
        fontWeight: 700,
    },
    measureCardBase: {
        padding: '0.75rem',
        background: 'var(--bg-secondary)',
        borderRadius: 'var(--radius-2xl)',
        transition: 'all var(--transition-fast)',
        cursor: 'pointer',
        position: 'relative',
        overflow: 'hidden',
        border: '1px solid rgba(255,255,255,0.05)',
    },
    playButton: {
        flex: 1,
        padding: '0.25rem',
        fontSize: '0.65rem',
        backgroundColor: 'transparent',
        borderRadius: '6px',
        cursor: 'pointer',
        transition: 'all var(--transition-fast)',
        fontWeight: 600,
    },
    numberBadgeBase: {
        position: 'absolute',
        top: '0.5rem',
        right: '0.5rem',
        color: 'white',
        borderRadius: '50%',
        width: '26px',
        height: '26px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: '0.65rem',
        fontWeight: 'bold',
        cursor: 'pointer',
        transition: 'all var(--transition-fast)',
        zIndex: 10,
    },
    timelineBar: {
        marginTop: '0.5rem',
        height: '3px',
        backgroundColor: 'rgba(255,255,255,0.05)',
        position: 'relative',
        borderRadius: '2px',
    },
    timelineDotBase: {
        position: 'absolute',
        width: '8px',
        height: '8px',
        borderRadius: '50%',
        border: '1.5px solid var(--bg-secondary)',
    },
    tipCard: {
        display: 'flex',
        gap: '0.75rem',
        padding: '0.75rem 1rem',
        background: 'var(--bg-secondary)',
        borderRadius: 'var(--radius-2xl)',
        border: '1px solid rgba(255,255,255,0.05)',
        alignItems: 'center',
    },
};
